language: bash
env:
      global:
      - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
      - CACHE="$HOME/.cache/entities"
      - XML_CATALOG_FILES="catalog.xml"

dist: yakkety

cache:
  directories:
    - $CACHE

before_script:
    - cat /etc/os-release
    - echo $TRAVIS_COMMIT
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ precise main universe restricted multiverse"
    # - sudo apt-get update
    - sudo apt-get install -y xml-core libxml2-utils libxml2-dev

script:
    - xmllint --version
    - ./travis/travis.sh travis/test.xml
