---
name: "DocBook/AsciiDoc validation"
description: "Validate DocBook/AsciiDoc documents with DAPS"
author: "@tomschr/@sknorr"
inputs:

  dc-files:
    description: "DC files to check."
    required: true

  validate-ids:
    description: "Check if all referenced xml:ids adhere to schema [a-z0-9-] (daps validate --validate-ids)"
    required: false
    default: true

  validate-images:
    description: "Check if all referenced images exist (daps validate --validate-images)"
    required: false
    default: true

  validate-tables:
    description: "Check if all tables within the document are valid (daps/libexec/validate-tables.py)"
    required: false
    default: true

  xml-schema:
    description: "XML schema to use for validation ('geekodoc1', 'docbook51'). DC file options take precedence over this setting. (Currently Noop.)"
    required: false
    default: "geekodoc1"

outputs:
  exitvalidate:
    description: "0 = validation successful, <0 = validation failed"


runs:
   using: docker
   image: "Dockerfile"
   args:
    - dc-files=${{ inputs.dc-files }}
    - validate-ids=${{ inputs.validate-ids }}
    - validate-images=${{ inputs.validate-images }}
    - validate-tables=${{ inputs.validate-tables }}
#    - xml-schema=${{ inputs.xml-schema }}
