sudo: required
language: bash
services:
  - docker

before_install:
  - wget https://raw.githubusercontent.com/openSUSE/doc-ci/develop/travis/travis.sh
  - docker build -t sle-doc-image .
  # list the installed packages (just for easier debugging)
  - docker run --rm -it sle-doc-image rpm -qa | sort

script:
  # It is important that we validate with and without remarks. Content between remarks is profiled out and this may
  - docker run --rm -it sle-doc-image /bin/bash -c 'travis.sh'
